version: "3.8"

services:
  users_service:
    build: ./users_service
    ports:
      - "8001:8001"
    networks:
      - mynetwork

  orders_service:
    build: ./orders_service
    ports:
      - "8002:8002"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
