version: "3.8"

services:
  redis:
    image: "redis:latest"
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  users_service:
    build: ./users_service
    ports:
      - "8001:8001"
    depends_on:
      - redis
    networks:
      - mynetwork

  orders_service:
    build: ./orders_service
    ports:
      - "8002:8002"
    depends_on:
      - redis
    networks:
      - mynetwork

  menu_service:
    build: ./menu_service
    ports:
      - "8003:8003"
    depends_on:
      - redis
    networks:
      - mynetwork

  payments_service:
    build: ./payments_service
    ports:
      - "8004:8004"
    depends_on:
      - redis
    networks:
      - mynetwork

  invoices_service:
    build: ./invoices_service
    ports:
      - "8005:8005"
    depends_on:
      - redis
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
